/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DjangoFormset {
        /**
          * Abort the current actions.
         */
        "abort": () => Promise<void>;
        "endpoint": string;
        "forceSubmission": boolean;
        "submit": () => Promise<Response | undefined>;
        "withholdMessages": boolean;
    }
}
declare global {
    interface HTMLDjangoFormsetElement extends Components.DjangoFormset, HTMLStencilElement {
    }
    var HTMLDjangoFormsetElement: {
        prototype: HTMLDjangoFormsetElement;
        new (): HTMLDjangoFormsetElement;
    };
    interface HTMLElementTagNameMap {
        "django-formset": HTMLDjangoFormsetElement;
    }
}
declare namespace LocalJSX {
    interface DjangoFormset {
        "endpoint"?: string;
        "forceSubmission"?: boolean;
        "withholdMessages"?: boolean;
    }
    interface IntrinsicElements {
        "django-formset": DjangoFormset;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "django-formset": LocalJSX.DjangoFormset & JSXBase.HTMLAttributes<HTMLDjangoFormsetElement>;
        }
    }
}
