# Generated by Django 5.1.7.dev20250211015633 on 2025-02-25 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Annotation'),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.45, message='You are too short.'), django.core.validators.MaxValueValidator(1.95, message='You are too tall.')], verbose_name='Height in meters'),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(42, message='You are too lightweight.'), django.core.validators.MaxValueValidator(95, message='You are too obese.')], verbose_name='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message="Phone number have 4-25 digits and may start with '+'.", regex='^\\+?[ 0-9.\\-]{4,25}$')], verbose_name='Phone Number'),
        ),
    ]
