name: Deploy django-formset

on: workflow_dispatch

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: "Deploy release"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy testapp to https://django-formset.fly.dev/
      run: flyctl deploy --remote-only
