name: Test django-formset's parsers

on:
  push:
    branches:
      - releases/*
    paths:
      - '/assets/*.pegjs'
      - '/client/tests/*.ts'
  pull_request:
    branches:
      - develop
    paths:
      - '/assets/*.pegjs'
      - '/client/tests/*.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Parsers
      run: |
        npm run tag-attributes
        npm run no-comments
    - name: Run tests
      run: |
        npm run testclient
